baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '2024-09-24 Meetup'

relativeURLs = true
uglyURLs = true

theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true